import type { MindMapArtifact, NotesArtifact } from '@/lib/types';

export function NotesSheet({ notes }: { notes: NotesArtifact }) { return <article className="worksheet mx-auto max-w-[210mm] bg-surface p-8 text-foreground shadow-sm sm:p-10"><header className="border-b-2 border-foreground pb-4"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted">Short notes</p><h1 className="mt-1 text-2xl font-bold">{notes.title}</h1></header><div className="mt-6 grid gap-5">{notes.sections.map((section) => <section key={section.heading}><h2 className="text-sm font-semibold text-accent">{section.heading}</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6">{section.points.map((point) => <li key={point}>{point}</li>)}</ul></section>)}</div><aside className="mt-7 rounded-lg border border-accent/30 bg-accent-soft p-4"><h2 className="text-sm font-semibold text-accent">Quick recap</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{notes.recap.map((item) => <li key={item}>{item}</li>)}</ul></aside></article>; }
export function MindMapSheet({ map }: { map: MindMapArtifact }) {
  const midpoint = Math.ceil(map.branches.length / 2);
  const columns = [map.branches.slice(0, midpoint), map.branches.slice(midpoint)];
  return <article className="worksheet mx-auto max-w-[210mm] bg-surface p-8 text-foreground shadow-sm sm:p-10"><header className="border-b-2 border-foreground pb-4"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted">Mind map</p><h1 className="mt-1 text-2xl font-bold">{map.title}</h1></header><div className="mindmap-layout mt-6 grid items-center gap-4 sm:grid-cols-[minmax(0,1fr)_10rem_minmax(0,1fr)]"><MindMapColumn branches={columns[0]} side="left" /><div className="mindmap-center order-first rounded-2xl bg-accent px-4 py-6 text-center text-base font-bold leading-snug text-white shadow-sm sm:order-none">{map.title}</div><MindMapColumn branches={columns[1]} side="right" /></div></article>;
}

function MindMapColumn({ branches, side }: { branches: MindMapArtifact['branches']; side: 'left' | 'right' }) {
  return <div className={`mindmap-column mindmap-column-${side} space-y-3`}>{branches.map((branch) => <section key={branch.label} className="mindmap-branch break-inside-avoid rounded-xl border border-line bg-background p-3"><h2 className="text-sm font-semibold leading-snug text-accent">{branch.label}</h2><ul className="mindmap-children mt-2 space-y-1">{branch.children.map((child) => <li key={child} className="mindmap-child rounded-md bg-surface px-2 py-1 text-xs leading-snug text-foreground">{child}</li>)}</ul></section>)}</div>;
}
